name: Build Bruce Firmware

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: |
          pip install --upgrade pip
          pip install platformio

      - name: Clean Build Only
        run: |
          rm -rf .pio/build
          rm -rf .pio/libdeps

      - name: Build Firmware
        run: pio run -e esp32-s3-devkitc-1-psram

      - name: Install esptool
        run: pip install esptool

      - name: Merge Firmware
        run: |
          esptool.py --chip esp32s3 merge_bin \
            -o .pio/build/esp32-s3-devkitc-1-psram/merged_firmware.bin \
            --flash_mode dio \
            --flash_freq 80m \
            --flash_size 16MB \
            0x0 .pio/build/esp32-s3-devkitc-1-psram/bootloader.bin \
            0x8000 .pio/build/esp32-s3-devkitc-1-psram/partitions.bin \
            0x10000 .pio/build/esp32-s3-devkitc-1-psram/firmware.bin

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bruce-firmware-s3
          path: |
            .pio/build/esp32-s3-devkitc-1-psram/merged_firmware.bin
            .pio/build/esp32-s3-devkitc-1-psram/firmware.bin
            .pio/build/esp32-s3-devkitc-1-psram/bootloader.bin
            .pio/build/esp32-s3-devkitc-1-psram/partitions.bin
            .pio/build/esp32-s3-devkitc-1-psram/firmware.elf
