name: Build Bruce Firmware

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
         run: |
          pip install --upgrade pip
          pip install platformio

      - name: Clean Build Only
        run: |
          rm -rf .pio/build
          rm -rf .pio/libdeps

      - name: Build Firmware
        run: pio run -e esp32-s3-devkitc-1-psram

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bruce-firmware-s3
          path: |
            .pio/build/esp32-s3-devkitc-1-psram/firmware.bin
            .pio/build/esp32-s3-devkitc-1-psram/bootloader.bin
            .pio/build/esp32-s3-devkitc-1-psram/partitions.bin
            .pio/build/esp32-s3-devkitc-1-psram/firmware.elf
